version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports: 
      - 5434:5432
    environment:
      POSGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks: 
      - nestjs-network
networks:
  nestjs-network: 