version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - ${DB_PORT}:5432
    environment:
      POSGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - nestjs-network
  dev:
    container_name: luckyking-api
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    # command: npm run start:debug
    # command: npm run start:prod
    command: npm run start:prod:pm2
    ports:
      - 3003:3001
      - 81:81
      # - 9229:9229
    networks:
      - nestjs-network
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
  nginx:
    container_name: nginx-proxy
    image: nginx:1.21.1-alpine
    ports:
      - 80:80
      - 445:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dev
    networks:
      - nestjs-network
networks:
  nestjs-network:
