-- AlterTable
ALTER TABLE "Lottery" ALTER COLUMN "bonusStatus" DROP NOT NULL,
ALTER COLUMN "periodCode" DROP NOT NULL,
ALTER COLUMN "periodTime" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "creataAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tradingCode" DROP NOT NULL,
ALTER COLUMN "surcharge" DROP NOT NULL,
ALTER COLUMN "dataPart" DROP NOT NULL,
ALTER COLUMN "rewardStatus" DROP NOT NULL;
