-- AlterTable
ALTER TABLE "Config" ADD COLUMN     "max3dSaleTime" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "max3dplusSaleTime" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "max3dproSaleTime" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "mega645SaleTime" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "power655SaleTime" INTEGER NOT NULL DEFAULT 30;
